### ISSUE TITLE
Update Kotlin Spring Example

### ISSUE THREAD

**Issue by zach-planet-nine** [planet-nine-app/sessionless#63]
The Kotlin Spring example was written before the examples were settled on so some of the naming isn't up-to-date. It needs to be updated to handle the routes:

POST /register with payload: 

 {
    pubKey: keys.pubKey,
    enteredText: "Foo",
    timestamp: new Date().getTime() + ''",
    signature: "..."
  };

POST /cool-stuff with payload:

{
    uuid,
    coolness: 'max',
    timestamp: new Date().getTime() + ''"
    signature: "..."
  };

Any of the CLIs (JS, Python, Rust) can be used to verify the example is working as expected.

**Comment by Galacticai** [comment]
is this resolved with #69 ?

**Comment by zach-planet-nine** [comment]
> is this resolved with #69 ?

yep!
