### ISSUE TITLE
Sessionless.org demo not working

### ISSUE THREAD

**Issue by PranavThampi** [planet-nine-app/sessionless#75]
I visited the sessionless.org website and the demo showcasing sessionless authentication isn't working. I can see a 404 error in the console.

<img width="1465" alt="image" src="https://github.com/user-attachments/assets/327529d0-73ab-4ea6-8ef3-2209683006e9">

**Comment by zach-planet-nine** [comment]
Thanks for bringing this to my attention. This should be fixed now. For anyone who stumbles upon this in the future, you can see the source for sessionless.org at https://www.github.com/planet-nine-app/sessionless-dot-org
